language: python
python:
  - "2.7"
  - "3.3"
install:
  - sudo apt-get install build-essential python-dev 
  - pip install -r requirements_dev.txt
  - python setup.py install
script: py.test 
branches:
  only:
    - master
    - develop
